<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PlaywrightFramework.Core\PlaywrightFramework.Core.csproj" />
    <ProjectReference Include="..\PlaywrightFramework.Api\PlaywrightFramework.Api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NJsonSchema" Version="11.6.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
